# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WriteMyName' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WriteMyName
  pod 'Alamofire'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessaging'

end
