# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SwirlFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwirlFramework
  
  pod 'Alamofire', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'IQKeyboardManagerSwift','6.5.0'
  pod 'TTGSnackbar'
  pod 'ObjectMapper', '~> 3.4'
  pod 'OTPTextField'
  pod 'FloatingHearts'

  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessaging'

  pod 'WriteMyName/Firebase/Firestore'
  pod 'WriteMyName/Firebase/Messaging'
  pod 'WriteMyName/Firebase/InAppMessaging'

  pod 'WriteMyName'

end
