# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SwirlFramework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwirlFramework
  
  pod 'Alamofire', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod "TTGSnackbar"
  pod 'IQKeyboardManagerSwift'
  pod 'ObjectMapper', '~> 3.4'
  pod 'OTPTextField'
  
  

end
