# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'GoSwirlLiveStream' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoSwirlLiveStream
  pod 'Firebase/Firestore', '10.12'
  pod 'Firebase/Messaging'
  pod 'Firebase/InAppMessaging'
  pod 'IQKeyboardManagerSwift','6.5.0'
  pod 'TTGSnackbar'
  pod 'SDWebImage'

end
